In [1]:
import sys
sys.path.append('/work/pikachu/utils/')
sys.path.append('/work/pikachu/third/')
sys.path.append('..')
from gezi.common import *
import gezi
from src.config import *
from src.util import *
gezi.init_flags()

INFO: Pandarallel will run on 16 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.


wandb: ERROR Unable to patch Tensorflow/Keras
exception while trying to patch_tf_keras
Traceback (most recent call last):
  File "/home/gezi/miniconda3/lib/python3.10/site-packages/wandb/integration/keras/keras.py", line 86, in patch_tf_keras
    from keras.engine import training
ModuleNotFoundError: No module named 'keras.engine'
wandb: ERROR Unable to patch Tensorflow/Keras
exception while trying to patch_tf_keras
Traceback (most recent call last):
  File "/home/gezi/miniconda3/lib/python3.10/site-packages/wandb/integration/keras/keras.py", line 86, in patch_tf_keras
    from keras.engine import training
ModuleNotFoundError: No module named 'keras.engine'
wandb: ERROR Unable to patch Tensorflow/Keras
exception while trying to patch_tf_keras
Traceback (most recent call last):
  File "/home/gezi/miniconda3/lib/python3.10/site-packages/wandb/integration/keras/keras.py", line 86, in patch_tf_keras
    from keras.engine import training
ModuleNotFoundError: No module named 'keras.engine'
[

In [2]:
df = pd.read_feather(f'{FLAGS.root}/train.fea')
df

index                                             frames  \
0          0  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...   
1          1  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...   
2          2  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...   
3          3  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...   
4          4  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...   
...      ...                                                ...   
67203  67203  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...   
67204  67204  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...   
67205  67205  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...   
67206  67206  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...   
67207  67207  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...   

                                               cls_label    file_id  \
0      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  532011803   
1      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...  532011803   
2      [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  532011803   
3      [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  532011803   
4      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, ...  532011803   
...                                                  ...        ...   
67203  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...  566963657   
67204  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  566963657   
67205  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  566963657   
67206  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, ...  566963657   
67207  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  566963657   

       first_char  fold   idx  last_char  n_frames  n_frames_per_char  \
0              54     0  4463         36         5           0.192308   
1              38     0  4600         17       189           7.875000   
2              22     0  4378         51       221           8.185185   
3              23     0  4429         20         6           0.272727   
4              48     0  4595         47       193          10.157895   
...           ...   ...   ...        ...       ...                ...   
67203          16     0  4948         14        35           7.000000   
67204          37     0  5102         43       114           6.000000   
67205          18     0  5071         51        98           5.764706   
67206          10     0  4900         19       174          12.428572   
67207          21     0  4901         51        82           4.555555   

       participant_id                       phrase  \
0                  71   www.gesundheitsberatung.de   
1                  68     gamis-hari-old-fuchsia-2   
2                 141  7198 northeast 371st street   
3                  92       8370 ross lake twp 205   
4                  81          q-wiatraki/?amp=amp   
...               ...                          ...   
67203             113                        1635/   
67204              73          frederick mcconnell   
67205             143            3936 ermine court   
67206               1               +66-13-0443-04   
67207             236           66 belspring court   

                                                 phrase_  phrase_dup  \
0      [55, 55, 55, 14, 39, 37, 51, 53, 46, 36, 40, 3...           1   
1      [39, 33, 45, 41, 51, 13, 40, 33, 50, 41, 13, 4...           1   
2      [23, 17, 25, 24, 1, 46, 47, 50, 52, 40, 37, 33...           1   
3      [24, 19, 23, 16, 1, 50, 47, 51, 51, 1, 44, 33,...           1   
4      [49, 13, 55, 41, 33, 52, 50, 33, 43, 41, 15, 2...           0   
...                                                  ...         ...   
67203  [17, 22, 19, 21, 15, 60, 0, 0, 0, 0, 0, 0, 0, ...           1   
67204  [38, 50, 37, 36, 37, 50, 41, 35, 43, 1, 45, 35...           0   
67205  [19, 25, 19, 22, 1, 37, 50, 45, 41, 46, 37, 1,...           1   
67206  [11, 22, 22, 13, 17, 19, 13, 16, 20, 20, 19, 1...           0   
67207  [22, 22, 1, 34, 37, 44, 

In [3]:
from datasets import Dataset
ds = Dataset.from_pandas(df)

In [4]:
ds = ds.with_format('tf')

In [5]:
ds[0]['phrase_']

<tf.Tensor: shape=(32,), dtype=int64, numpy=
array([55, 55, 55, 14, 39, 37, 51, 53, 46, 36, 40, 37, 41, 52, 51, 34, 37,
       50, 33, 52, 53, 46, 39, 14, 36, 37, 60,  0,  0,  0,  0,  0])>

In [6]:
len(ds)

67208

In [7]:
ds2 = ds.to_tf_dataset(batch_size=128)

In [8]:
for i, item in enumerate(ds):
  print(item['index'])
  if i == 10:
    break

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(10, shape=(), dtype=int64)


In [9]:
ds = ds.shuffle(seed=42)
for i, item in enumerate(ds):
  print(item['index'])
  if i == 10:
    break

tf.Tensor(61756, shape=(), dtype=int64)
tf.Tensor(17180, shape=(), dtype=int64)
tf.Tensor(62630, shape=(), dtype=int64)
tf.Tensor(36632, shape=(), dtype=int64)
tf.Tensor(49848, shape=(), dtype=int64)
tf.Tensor(17439, shape=(), dtype=int64)
tf.Tensor(63272, shape=(), dtype=int64)
tf.Tensor(19883, shape=(), dtype=int64)
tf.Tensor(4897, shape=(), dtype=int64)
tf.Tensor(36660, shape=(), dtype=int64)
tf.Tensor(1553, shape=(), dtype=int64)


In [10]:
for i, item in enumerate(ds):
  print(item['index'])
  if i == 10:
    break

tf.Tensor(61756, shape=(), dtype=int64)
tf.Tensor(17180, shape=(), dtype=int64)
tf.Tensor(62630, shape=(), dtype=int64)
tf.Tensor(36632, shape=(), dtype=int64)
tf.Tensor(49848, shape=(), dtype=int64)
tf.Tensor(17439, shape=(), dtype=int64)
tf.Tensor(63272, shape=(), dtype=int64)
tf.Tensor(19883, shape=(), dtype=int64)
tf.Tensor(4897, shape=(), dtype=int64)
tf.Tensor(36660, shape=(), dtype=int64)
tf.Tensor(1553, shape=(), dtype=int64)


In [11]:
ds.column_names

['index',
 'frames',
 'cls_label',
 'file_id',
 'first_char',
 'fold',
 'idx',
 'last_char',
 'n_frames',
 'n_frames_per_char',
 'participant_id',
 'phrase',
 'phrase_',
 'phrase_dup',
 'phrase_len',
 'phrase_type',
 'phrase_type_',
 'sequence_id',
 'weight']

In [12]:
# from src.tf.preprocess import PreprocessLayer
# preprocesor = PreprocessLayer(320)
# ds = ds.map(lambda x: preprocesor(x['frames']), batched=True)

In [13]:
from src.dataset import PreProcssor
preprocesor = PreProcssor()

In [14]:
  # ds = ds.map(decode_tfrec, tf.data.AUTOTUNE)
  # ds = ds.map(lambda x: preprocess(x, augment=augment, max_len=max_len), tf.data.AUTOTUNE)

  # if repeat: 
  #     ds = ds.repeat()
      
  # if shuffle:
  #     ds = ds.shuffle(shuffle)
  #     options = tf.data.Options()
  #     options.experimental_deterministic = (False)
  #     ds = ds.with_options(options)
  
  # if batch_size:
  #     ds = ds.padded_batch(batch_size, padding_values=PAD, padded_shapes=([max_len,CHANNELS],[NUM_CLASSES]), drop_remainder=drop_remainder)

ds2 = ds.to_tf_dataset(batch_size=1)
ds2 = ds2.map(preprocesor, tf.data.AUTOTUNE)
ds2 = ds2.shuffle(10240)
options = tf.data.Options()
options.experimental_deterministic = (False)
ds2 = ds2.prefetch(tf.data.AUTOTUNE)
ds2 = ds2.padded_batch(128, drop_remainder=True)

In [15]:
m = iter(ds2).next()

In [16]:
for key, val in m[0].items():
  print(key, val.shape)

index (128, 1)
frames (128, 128, 176)
cls_label (128, 1, 59)
file_id (128, 1)
first_char (128, 1)
fold (128, 1)
idx (128, 1)
last_char (128, 1)
n_frames (128, 1)
n_frames_per_char (128, 1)
participant_id (128, 1)
phrase (128, 1)
phrase_ (128, 1, 32)
phrase_dup (128, 1)
phrase_len (128, 1)
phrase_type (128, 1)
phrase_type_ (128, 1)
sequence_id (128, 1)
weight (128, 1)


In [17]:
m[0]['frames']

<tf.Tensor: shape=(128, 128, 176), dtype=float32, numpy=
array([[[0.        , 0.        , 0.        , ..., 0.70683056,
         0.7065306 , 0.70642596],
        [0.        , 0.        , 0.        , ..., 0.70331323,
         0.704155  , 0.7051564 ],
        [0.        , 0.        , 0.        , ..., 0.70279586,
         0.70291483, 0.70327395],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]],

       [[0.        , 0.        , 0.        , ..., 0.47675666,
         0.47457018, 0.474172  ],
        [0.        , 0.        , 0.        , ..., 0.47665372,
         0.47419527, 0.47366825],
        [0.        , 0.        , 0.        , ..., 0.47695163,
         0.47453222, 0.4739863 ],
        ...,
        [0.        , 0.        , 0.        , ..., 0

In [18]:
m[0]['phrase_']

<tf.Tensor: shape=(128, 1, 32), dtype=int64, numpy=
array([[[55, 55, 55, ...,  0,  0,  0]],

       [[40, 47, 44, ...,  0,  0,  0]],

       [[24, 22, 23, ...,  0,  0,  0]],

       ...,

       [[36, 41, 51, ...,  0,  0,  0]],

       [[40, 52, 52, ...,  0,  0,  0]],

       [[45, 47, 34, ...,  0,  0,  0]]])>

In [19]:
ds.to_tf_dataset?

Signature:
ds.to_tf_dataset(
    batch_size: int,
    columns: Union[str, List[str], NoneType] = None,
    shuffle: bool = False,
    collate_fn: Optional[Callable] = None,
    drop_remainder: bool = False,
    collate_fn_args: Optional[Dict[str, Any]] = None,
    label_cols: Union[str, List[str], NoneType] = None,
    prefetch: bool = True,
    num_workers: int = 0,
    num_test_batches: int = 20,
)
Docstring:
Create a `tf.data.Dataset` from the underlying Dataset. This `tf.data.Dataset` will load and collate batches from
the Dataset, and is suitable for passing to methods like `model.fit()` or `model.predict()`. The dataset will yield
`dicts` for both inputs and labels unless the `dict` would contain only a single key, in which case a raw
`tf.Tensor` is yielded instead.

Args:
    batch_size (`int`):
        Size of batches to load from the dataset.
    columns (`List[str]` or `str`, *optional*):
        Dataset column(s) to load in the `tf.data.Dataset`.
        Column names that ar

In [20]:
ds2 = ds.to_tf_dataset(batch_size=128)
ds2

<_PrefetchDataset element_spec={'index': TensorSpec(shape=(None,), dtype=tf.int64, name=None), 'frames': TensorSpec(shape=(None, None, 176), dtype=tf.float32, name=None), 'cls_label': TensorSpec(shape=(None, 59), dtype=tf.int64, name=None), 'file_id': TensorSpec(shape=(None,), dtype=tf.int64, name=None), 'first_char': TensorSpec(shape=(None,), dtype=tf.int64, name=None), 'fold': TensorSpec(shape=(None,), dtype=tf.int64, name=None), 'idx': TensorSpec(shape=(None,), dtype=tf.int64, name=None), 'last_char': TensorSpec(shape=(None,), dtype=tf.int64, name=None), 'n_frames': TensorSpec(shape=(None,), dtype=tf.int64, name=None), 'n_frames_per_char': TensorSpec(shape=(None,), dtype=tf.float32, name=None), 'participant_id': TensorSpec(shape=(None,), dtype=tf.int64, name=None), 'phrase': TensorSpec(shape=(None,), dtype=tf.string, name=None), 'phrase_': TensorSpec(shape=(None, 32), dtype=tf.int64, name=None), 'phrase_dup': TensorSpec(shape=(None,), dtype=tf.int64, name=None), 'phrase_len': Tensor

In [21]:
ds2 = ds2.map(preprocesor, tf.data.AUTOTUNE)
ds2

<_ParallelMapDataset element_spec=({'index': TensorSpec(shape=(None,), dtype=tf.int64, name=None), 'frames': TensorSpec(shape=(128, 176), dtype=tf.float32, name=None), 'cls_label': TensorSpec(shape=(None, 59), dtype=tf.int64, name=None), 'file_id': TensorSpec(shape=(None,), dtype=tf.int64, name=None), 'first_char': TensorSpec(shape=(None,), dtype=tf.int64, name=None), 'fold': TensorSpec(shape=(None,), dtype=tf.int64, name=None), 'idx': TensorSpec(shape=(None,), dtype=tf.int64, name=None), 'last_char': TensorSpec(shape=(None,), dtype=tf.int64, name=None), 'n_frames': TensorSpec(shape=(None,), dtype=tf.int64, name=None), 'n_frames_per_char': TensorSpec(shape=(None,), dtype=tf.float32, name=None), 'participant_id': TensorSpec(shape=(None,), dtype=tf.int64, name=None), 'phrase': TensorSpec(shape=(None,), dtype=tf.string, name=None), 'phrase_': TensorSpec(shape=(None, 32), dtype=tf.int64, name=None), 'phrase_dup': TensorSpec(shape=(None,), dtype=tf.int64, name=None), 'phrase_len': TensorSpe

In [22]:
ds2 = ds2.shuffle(10240)
options = tf.data.Options()
options.experimental_deterministic = (False)
ds2 = ds2.prefetch(tf.data.AUTOTUNE)
ds2 = ds2.padded_batch(128, drop_remainder=True)
ds2

<_PaddedBatchDataset element_spec=({'index': TensorSpec(shape=(128, None), dtype=tf.int64, name=None), 'frames': TensorSpec(shape=(128, 128, 176), dtype=tf.float32, name=None), 'cls_label': TensorSpec(shape=(128, None, 59), dtype=tf.int64, name=None), 'file_id': TensorSpec(shape=(128, None), dtype=tf.int64, name=None), 'first_char': TensorSpec(shape=(128, None), dtype=tf.int64, name=None), 'fold': TensorSpec(shape=(128, None), dtype=tf.int64, name=None), 'idx': TensorSpec(shape=(128, None), dtype=tf.int64, name=None), 'last_char': TensorSpec(shape=(128, None), dtype=tf.int64, name=None), 'n_frames': TensorSpec(shape=(128, None), dtype=tf.int64, name=None), 'n_frames_per_char': TensorSpec(shape=(128, None), dtype=tf.float32, name=None), 'participant_id': TensorSpec(shape=(128, None), dtype=tf.int64, name=None), 'phrase': TensorSpec(shape=(128, None), dtype=tf.string, name=None), 'phrase_': TensorSpec(shape=(128, None, 32), dtype=tf.int64, name=None), 'phrase_dup': TensorSpec(shape=(128,