In [1]:
import sys
sys.path.append('/work/pikachu/utils/')
sys.path.append('/work/pikachu/third/')
sys.path.append('/work/pikachu/projects/kaggle/aslfr/third/NeMo')
sys.path.append('..')
from gezi.common import *
import gezi
from src.config import *
from src.vis import *
gezi.init_flags()

INFO: Pandarallel will run on 16 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.


wandb: ERROR Unable to patch Tensorflow/Keras
exception while trying to patch_tf_keras
Traceback (most recent call last):
  File "/home/gezi/miniconda3/lib/python3.10/site-packages/wandb/integration/keras/keras.py", line 86, in patch_tf_keras
    from keras.engine import training
ModuleNotFoundError: No module named 'keras.engine'
wandb: ERROR Unable to patch Tensorflow/Keras
exception while trying to patch_tf_keras
Traceback (most recent call last):
  File "/home/gezi/miniconda3/lib/python3.10/site-packages/wandb/integration/keras/keras.py", line 86, in patch_tf_keras
    from keras.engine import training
ModuleNotFoundError: No module named 'keras.engine'
wandb: ERROR Unable to patch Tensorflow/Keras
exception while trying to patch_tf_keras
Traceback (most recent call last):
  File "/home/gezi/miniconda3/lib/python3.10/site-packages/wandb/integration/keras/keras.py", line 86, in patch_tf_keras
    from keras.engine import training
ModuleNotFoundError: No module named 'keras.engine'
[

In [2]:
x = nn.Embedding(4, 1)
x.weight.data.fill_(0.5)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000]])

In [8]:
x(torch.range(0,3,dtype=torch.long)[0])

tensor([0.5000], grad_fn=<EmbeddingBackward0>)

In [2]:
tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [3]:
tf.random.shuffle(tf.range(10))

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([3, 5, 0, 6, 9, 2, 8, 7, 1, 4], dtype=int32)>

In [2]:
from einops import rearrange

In [3]:
seq = torch.arange(5)
dist = rearrange(seq, 'i -> i ()') - rearrange(seq, 'j -> () j')
dist

tensor([[ 0, -1, -2, -3, -4],
        [ 1,  0, -1, -2, -3],
        [ 2,  1,  0, -1, -2],
        [ 3,  2,  1,  0, -1],
        [ 4,  3,  2,  1,  0]])

In [4]:
rearrange(seq, 'i -> i ()')

tensor([[0],
        [1],
        [2],
        [3],
        [4]])

In [5]:
rearrange(seq, 'i -> i ()').shape

torch.Size([5, 1])

In [6]:
seq

tensor([0, 1, 2, 3, 4])

In [ ]:
rearrange(seq, 'j -> () j')

In [ ]:
seq.unsqueeze(-1) - seq[None]

In [ ]:
rel_pos_emb = nn.Embedding(2 * 16 + 1, 64)
rel_pos_emb

In [53]:
#einsum('b h n d, n r d -> b h n r', q, rel_pos_emb) * self.scale
x = torch.randn(2, 3, 4, 5)
y = torch.randn(4, 6, 5)

In [34]:
# n b h d, n, d, r -> n b h r

In [55]:
x2 = x.permute(2, 0, 1, 3)
x2.shape

torch.Size([4, 2, 3, 5])

In [56]:
b, h, n, d = x.shape[0], x.shape[1], x.shape[2], x.shape[3]
r = y.shape[1]
b, h, n, d ,r

(2, 3, 4, 5, 6)

In [57]:
x3 = x2.view(n, -1, d)
x3.shape # n, b*h, d

torch.Size([4, 6, 5])

In [58]:
#n, b*h, d  | n, d, r -> n, b*h, r
z = torch.matmul(x3, y.permute(0,2,1))
z.shape

torch.Size([4, 6, 6])

In [59]:
z.view(n, b, h, r).shape

torch.Size([4, 2, 3, 6])

In [60]:
z.view(n, b, h, r).permute(1,2,0,3).shape

torch.Size([2, 3, 4, 6])

In [61]:
z.view(n, b, h, r).permute(1,2,0,3)

tensor([[[[ 3.6069, -0.1010,  4.5907,  1.4409, -0.3374, -0.4687],
          [ 0.7922, -0.5243,  0.4649, -4.5525, -0.3684, -0.0769],
          [-5.0455, -3.7415,  0.8662, -0.7653, -0.8775,  2.6790],
          [-0.3818, -0.5261,  0.9918,  0.1970, -1.3475,  0.5043]],

         [[ 5.8555,  1.6040,  1.4877,  1.4559, -3.0550,  1.3703],
          [ 0.5775,  1.3960, -0.1979, -0.6887,  0.4227,  1.3436],
          [-2.5166, -2.9616,  2.5767, -1.8824,  1.7688, -1.6250],
          [ 2.5197, -5.2587,  0.8104,  2.0734, -2.4606, -3.8890]],

         [[-3.3692, -0.8103, -2.8108,  0.4985, -0.7990, -0.4578],
          [-0.0634,  1.5177, -1.1966,  5.0308,  0.4006,  3.1809],
          [-1.0388,  0.0606,  0.9913,  0.4082, -1.4214,  0.5557],
          [ 0.0834, -0.0322, -0.3532, -1.0801,  2.2203,  0.4495]]],


        [[[ 1.2568,  1.2199,  2.2575, -4.1517, -0.0655, -1.0283],
          [ 2.6378,  1.2028,  0.0591,  1.5880, -0.3620, -2.1721],
          [ 1.7675,  3.6259,  0.0406,  2.7281, -1.4146,  0.0640],
  

In [ ]:
torch.matmul(x3, y.permute(0,2,1)).view()

In [14]:
torch.matmul(x, y[0].permute(1,0)).shape

torch.Size([2, 3, 4, 6])

In [8]:
torch.matmul(x.unsqueeze(3), y.permute(0,2,1)).squeeze(-2).shape

torch.Size([2, 3, 4, 6])

In [51]:
torch.matmul(x.unsqueeze(3), y.permute(0,2,1)).squeeze(-2)

tensor([[[[-1.9550e+00,  3.4765e+00,  1.4760e+00, -1.6681e-01, -1.7891e+00,
           -1.8253e+00],
          [ 2.0979e+00, -5.8569e-01,  1.9579e+00,  1.8438e+00, -1.5411e+00,
            5.2032e-01],
          [ 8.9296e-01,  7.3691e-01,  9.1067e-01, -8.9252e-01,  9.0295e-01,
            4.5908e-01],
          [-8.4542e-01, -1.6882e+00,  3.6080e+00,  5.7835e-01,  2.2950e+00,
           -2.9823e+00]],

         [[ 2.6324e-01,  3.1066e+00,  2.2120e+00, -2.1137e-01, -4.6306e-01,
           -3.3934e+00],
          [-4.4694e+00,  6.0844e-01, -3.0232e+00, -1.2968e+00, -2.0171e+00,
            4.5604e+00],
          [ 1.5183e+00,  5.8577e-01, -2.3140e+00,  2.8674e+00, -5.7707e+00,
            3.3515e-01],
          [-2.6296e+00, -2.2161e+00,  2.5077e+00, -2.1133e-02,  2.5321e+00,
            1.4492e+00]],

         [[-4.4617e+00,  2.3848e+00, -3.7521e+00,  2.0180e+00, -1.8481e+00,
           -1.7289e+00],
          [ 4.6432e+00, -9.3029e+00, -3.6852e+00,  2.2391e+00, -2.8566e+00,
           

In [10]:
torch.einsum('b h n d, n r d -> b h n r', x, y).shape

torch.Size([2, 3, 4, 6])

In [54]:
torch.einsum('b h n d, n r d -> b h n r', x, y)

tensor([[[[ 3.6069, -0.1010,  4.5907,  1.4409, -0.3374, -0.4687],
          [ 0.7922, -0.5243,  0.4649, -4.5525, -0.3684, -0.0769],
          [-5.0455, -3.7415,  0.8662, -0.7653, -0.8775,  2.6790],
          [-0.3818, -0.5261,  0.9918,  0.1970, -1.3475,  0.5043]],

         [[ 5.8555,  1.6040,  1.4877,  1.4559, -3.0550,  1.3703],
          [ 0.5775,  1.3960, -0.1979, -0.6887,  0.4227,  1.3436],
          [-2.5166, -2.9616,  2.5767, -1.8824,  1.7688, -1.6250],
          [ 2.5197, -5.2587,  0.8104,  2.0734, -2.4606, -3.8890]],

         [[-3.3692, -0.8103, -2.8108,  0.4985, -0.7990, -0.4578],
          [-0.0634,  1.5177, -1.1966,  5.0308,  0.4006,  3.1809],
          [-1.0388,  0.0606,  0.9913,  0.4082, -1.4214,  0.5557],
          [ 0.0834, -0.0322, -0.3532, -1.0801,  2.2203,  0.4495]]],


        [[[ 1.2568,  1.2199,  2.2575, -4.1517, -0.0655, -1.0283],
          [ 2.6378,  1.2028,  0.0591,  1.5880, -0.3620, -2.1721],
          [ 1.7675,  3.6259,  0.0406,  2.7281, -1.4146,  0.0640],
  

In [ ]:
from nemo.collections.asr.parts.submodules.causal_convs import CausalConv2D

In [ ]:
from nemo.collections.asr.parts.submodules.subsampling import *

In [ ]:
x = torch.ones([1, 320, 192])

In [ ]:
StackingSubsampling?

In [ ]:
sampler = StackingSubsampling(2, 192, 128)

In [ ]:
a, b = sampler(x, torch.ones_like(x).sum(-1))
ic(a, b, a.shape, b.shape)

In [ ]:
ConvSubsampling?

In [ ]:
sampler = ConvSubsampling('vggnet', 2, 192, 256, 9)

In [ ]:
a, b = sampler(x, torch.ones_like(x).sum(-1))
ic(a, b, a.shape, b.shape)

In [ ]:
TimeReductionModule?

In [ ]:
sampler = TimeReductionModule(192, 256)
a = sampler(x)
ic(a)
ic(a[0].shape)

In [ ]:
stop

In [ ]:
d = pd.read_csv('../input/asl-fingerspelling/train2.csv')
d = d[d.fold==0]
d.head(20)

In [ ]:
inf = float("inf")
logits = tf.constant([[[   0., -inf, -inf],
                       [ -2.3, -inf, -0.1]],
                      [[ -inf, -0.5, -inf],
                       [ -inf, -inf, -0.1]],
                      [[ -inf, -inf, -inf],
                       [ -0.1, -inf, -2.3]]])
seq_lens = tf.constant([2, 3])
outputs = tf.nn.ctc_greedy_decoder(
    logits,
    seq_lens,
    blank_index=1)

In [ ]:
outputs

In [ ]:
logits.shape

In [ ]:
tf.keras.backend.ctc_decode(logits, [2, 2, 2], greedy=True, beam_width=100, top_paths=1)

In [ ]:
x = tf.ones((6, 10, 3))
x

In [ ]:
drop = tf.keras.layers.Dropout(0.2, noise_shape=(None, 1, 1))

In [ ]:
y = drop(x, training=True)
y

In [ ]:
tf.reduce_mean(drop(x, training=True))

In [ ]:
drop(x, training=True)

In [ ]:
y[2]

In [ ]:
def noise_drop(x, drop_rate):
  mask = torch.ones_like(x[:,:1,:1])
  mask = F.dropout(mask, drop_rate)
  return x * mask

In [ ]:
class NoiseDropout(nn.Module):
    def __init__(self, p=0.5):
        super().__init__()
        self.p = p
        self.dropout = nn.Dropout(p)

    def forward(self, x):
        if not self.training or self.p == 0.:
            return x
        mask = torch.ones_like(x[:,:1,:1])
        mask = self.dropout(mask)
        return x * mask

In [ ]:
x2 = torch.ones(6, 10, 3)
x2 

In [ ]:
torch.ones_like(x2[:,:1,:1]).shape

In [ ]:
NoiseDropout(0.2)(x2).mean()

In [ ]:
NoiseDropout(0.2)(x2)

In [ ]:
noise_drop(x2, 0.2).mean()

In [ ]:
x = tf.random.normal((1, 10, 3))

In [ ]:
x

In [ ]:
l = tf.split(x, x.shape[1], 1)
l = [
tf.random.categorical(
    tf.squeeze(a, 1), 1
)
for a in l
]
tf.concat(l, axis=-1)

In [ ]:
size = (0.2, 0.4)
mask_value = 0.
l = tf.shape(x)[1]
mask_size = tf.random.uniform((), *size)
mask_size = tf.cast(tf.cast(l, tf.float32) * mask_size, tf.int32)
mask_offset = tf.random.uniform((), 0, tf.clip_by_value(l-mask_size,1,l), dtype=tf.int32)
tf.tensor_scatter_nd_update(x, tf.range(mask_offset, mask_offset+mask_size)[None,...,None],tf.fill([tf.shape(x)[0], mask_size, tf.shape(x)[-1]],mask_value))

In [ ]:
mask_offset

In [ ]:
mask_size

In [ ]:
tf.range(1,4)

In [ ]:
tf.range(mask_offset, mask_offset+mask_size)

In [ ]:
tf.range(mask_offset, mask_offset+mask_size)[None,...,None]

In [ ]:
tf.fill([tf.shape(x)[0], mask_size, tf.shape(x)[-1]],mask_value)

In [ ]:
tf.tensor_scatter_nd_update(x[0], tf.range(mask_offset, mask_offset+mask_size)[...,None],tf.fill([mask_size, tf.shape(x)[-1]],mask_value))

In [ ]:
import melt as mt
ratio = tf.random.uniform((1,), 0, 0.15)
mask = tf.random.uniform((mt.get_shape(x, 0), mt.get_shape(x, 1), mt.get_shape(x, 2)))  > ratio
mask = tf.cast(mask, dtype=x.dtype)
mask
# rmask = FLAGS.unk_id * (1 - mask)
# x = (x * mask + rmask) * x_mask

In [ ]:
import melt as mt
ratio = tf.random.uniform((1,), 0, 0.15)
mask = tf.random.uniform((mt.get_shape(x, 0), mt.get_shape(x, 1), 1))  > ratio
mask = tf.cast(mask, dtype=x.dtype)
mask
# rmask = FLAGS.unk_id * (1 - mask)
# x = (x * mask + rmask) * x_mask

In [ ]:
x *= mask
x

In [ ]:
import melt as mt
ratio = tf.random.uniform((1,), 0, 0.15)
ic(ratio)
mask = tf.random.uniform((mt.get_shape(x, 0), 1, mt.get_shape(x, 2)))  > ratio
mask = tf.cast(mask, dtype=x.dtype)
mask

In [ ]:
x = tf.ones((1, 10, 3))
x * mask

In [ ]:
x = tf.nn.dropout(tf.ones((1, 10)), 0.15)
x 

In [ ]:
x == 0

In [ ]:
tf.ones((1, 10))

In [ ]:
tf.nn.dropout??

In [ ]:
shear_x = 0.2
shear_y = 0
tf.identity([
            [1.,shear_x],
            [shear_y,1.]
        ])